# Generated by Django 3.1.7 on 2021-04-04 18:08

from django.db import migrations


def fill_currencies(apps, schema_editor):
    supported_currencies = [('EUR', 'Euro', '€'), ('CHF', 'Swiss Franc', 'Fr'), 
                            ('USD', 'American Dollars', '$'), ('GBP', 'Pound Sterling', '£')]
    Currency = apps.get_model('exchanger', 'Currency')
    for currency in supported_currencies:
        currency_obj = Currency(code=currency[0], name=currency[1], symbol=currency[2])
        currency_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_currencies)
    ]
