# Generated by Django 3.1.7 on 2021-04-04 18:26

from django.db import migrations


def create_initial_providers(apps, schema_editor):
    CurrencyProvider = apps.get_model('exchanger', 'CurrencyProvider')
    fixerio_provider = CurrencyProvider(name='FixerIo', priority=0, provider_type= 'fixerio')
    fixerio_provider.save()
    mock_provider = CurrencyProvider(name='Mock', priority=1, provider_type= 'mock')
    mock_provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_initial_data'),
    ]

    operations = [
        migrations.RunPython(create_initial_providers)
    ]
